name: church_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.8
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.8
  cloud_firestore: ^4.4.3
  infinite_scroll_pagination: ^3.2.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  http: ^0.13.5
  shared_preferences: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/church_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  assets:
    - assets/
  uses-material-design: true
